partnersite_profile.partnersite_profiles.*:
  type: config_entity
  label: 'Partnersite profiles config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    auth_div:
      type: integer
      label: 'Authentication Division'
    auth_secret:
      type: string
      label: 'Authentication Secret Key'
    auth_mapping_hash:
      type: string
      label: 'Authentication HASH map'
    auth_timestamp_expiry:
      type: integer
      label: 'Expiry'
    auth_hash_logic:
      type: string
      label: 'Expiry'
    partner_email:
      type: string
      label: 'Partner Email'
    uuid:
      type: string
